name: monero
version: "0.10.1"
summary: Monero Daemon and GUI
description: The secure, private, untraceable cryptocurrency
confinement: strict

apps:
  monerod:
    command: monerod
    plugs: [network-bind,network,home]
  monero-wallet-cli:
    command: monero-wallet-cli
    plugs: [network,home]
  monero-wallet-gui:
    command: monero-wallet-gui
    plugs: [x11,home]

parts:
  monero:
    plugin: make
    source: https://github.com/monero-project/monero/archive/v0.10.1.tar.gz
    filesets:
      binaries:
        - build/release/bin/*
    artifacts:
      - build/release/lib/libwallet.a
      - $binaries
    build-packages:
      - gcc 
      - g++
      - cmake
      - libboost-all-dev 
      - libdb5.3-dev
      - libunbound-dev
      - libunwind8-dev
      - libssl-dev

  monero-core:
    plugin: qmake
    qt-version: qt5
    source: https://github.com/monero-project/monero-core/archive/v0.0-beta-1.tar.gz
    build: |
      ./build.sh
    install: | 
      mv ./release/bin/monero-wallet-gui $SNAPCRAFT_PART_INSTALL/bin/
    after: 
      - monero
      - desktop-qt5
    build-packages:
      - qtbase5-dev 
      - qtdeclarative5-dev 
      - qttools5-dev-tools 
    stage-packages:
      - qml-module-qtquick-controls 
      - qml-module-qtquick-xmllistmodel 
      - qml-module-qtquick-dialogs 
      - qml-module-qt-labs-settings 
      - libqt5qml-graphicaleffects

